name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@3.8.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          command: publish