name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install Wrangler CLI
      run: npm install -g wrangler

    - name: Authenticate with Cloudflare
      run: wrangler login
      env:
        CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

    - name: Publish Worker
      run: wrangler publish
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
